services:
  db:
    container_name: automata-todo-db
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_USER=docker
      - POSTGRESQL_DATABASE=automata-todo
    ports:
      - 5432:5432
    volumes:
      - db-data:/bitnami/postgresql
    networks:
      - automata-todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-test:
    container_name: automata-todo-test-db
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_USER=docker
      - POSTGRESQL_DATABASE=automata-todo-test
    ports:
      - 5433:5432
    volumes:
      - db-test-data:/bitnami/postgresql
    networks:
      - automata-todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      timeout: 5s
      retries: 5

  # api:
  #   container_name: automata-todo-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api
  #   env_file: ./apps/api/.env.docker
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - db
  #   networks:
  #     - automata-todo-network

  # web:
  #   container_name: automata-todo-web
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.web
  #   env_file: ./apps/web/.env.docker
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - api
  #   links:
  #     - api
  #   networks:
  #     - automata-todo-network

networks:
  automata-todo-network:
    driver: bridge

volumes:
  db-data:
  db-test-data: